services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_SOCKET_URL=https://api-chat-app-production-14a5.up.railway.app
    restart: unless-stopped
